services:
  database:
    image: 'busybox'
    container_name: ${DC_ORO_NAME:-unnamed}_database
    command: sleep infinity
    networks:
      - 'appnet'
    restart: always
    healthcheck:
      test: "sh -c 'exit 0'"
