services:
  ssh:
    container_name: "${DC_ORO_NAME:-unnamed}_ssh_${DC_ORO_PHP_VERSION:-8.3}-${DC_ORO_NODE_VERSION:-20}-${DC_ORO_COMPOSER_VERSION:-2}"
    hostname: ssh.${DC_ORO_NAME:-unnamed}.docker.local
    image: ghcr.io/digitalspacestdio/orodc-php-node-symfony:${DC_ORO_PHP_VERSION:-8.3}-${DC_ORO_NODE_VERSION:-20}-${DC_ORO_COMPOSER_VERSION:-2}-${DC_ORO_PHP_DIST:-alpine}
    build:
      context: "${DC_ORO_CONFIG_DIR:-.}/docker/php-node-symfony"
      dockerfile: Dockerfile.${DC_ORO_PHP_VERSION:-8.3}.${DC_ORO_PHP_DIST:-alpine}
      args:
        APP_DIR: "${DC_ORO_APPDIR:-/var/www}"
        PHP_VERSION: "${DC_ORO_PHP_VERSION:-8.3}"
        NODE_VERSION: "${DC_ORO_NODE_VERSION:-20}"
        PHP_USER_NAME: "${DC_ORO_PHP_USER_NAME:-developer}"
        PHP_USER_GROUP: "${DC_ORO_PHP_USER_GROUP:-developer}"
        PHP_UID: "${DC_ORO_PHP_UID:-1000}"
        PHP_GID: "${DC_ORO_PHP_GID:-1000}"
        COMPOSER_VERSION: "${DC_ORO_COMPOSER_VERSION:-2}"
    user: "root"
    command: docker-sshd
    volumes:
      - "appcode:${DC_ORO_APPDIR:-/var/www}"
      - "home-user:/home/${DC_ORO_PHP_USER_NAME:-developer}"
      - "home-root:/root"
      - "ssh-hostkeys:/etc/ssh/hostkeys"
      - "${DC_ORO_CONFIG_DIR:-.}/docker/php-node-symfony/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint:ro"
    working_dir: "${DC_ORO_APPDIR:-/var/www}"
    networks:
      - 'app'
    ports:
      - "${DC_ORO_SSH_BIND_HOST:-127.0.0.1}:${DC_ORO_PORT_SSH:-2222}:22"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      database:
        condition: service_healthy
      search:
        condition: service_healthy
      mq:
        condition: service_healthy
      redis:
        condition: service_healthy
      mail:
        condition: service_healthy
    environment:
      - 'APP_DIR=${DC_ORO_APPDIR:-/var/www}'
      - 'DC_ORO_APPDIR=${DC_ORO_APPDIR:-/var/www}'
      - 'DC_ORO_DATABASE_HOST=${DC_ORO_DATABASE_HOST:-database}'
      - 'DC_ORO_DATABASE_PORT=${DC_ORO_DATABASE_PORT:-3306}'
      - 'DC_ORO_DATABASE_USER=${DC_ORO_DATABASE_USER:-app}'
      - 'DC_ORO_DATABASE_PASSWORD=${DC_ORO_DATABASE_PASSWORD:-app}'
      - 'DC_ORO_DATABASE_DBNAME=${DC_ORO_DATABASE_DBNAME:-app}'
      - 'ORO_DB_URL=${DC_ORO_DATABASE_URI:-"postgres://${DC_ORO_DATABASE_USER:-app}:${DC_ORO_DATABASE_PASSWORD:-app}@${DC_ORO_DATABASE_HOST:-database}:${DC_ORO_DATABASE_PORT:-5432}/${DC_ORO_DATABASE_DBNAME:-app}"}'
      - 'ORO_DB_DSN=${DC_ORO_DATABASE_URI:-"postgres://${DC_ORO_DATABASE_USER:-app}:${DC_ORO_DATABASE_PASSWORD:-app}@${DC_ORO_DATABASE_HOST:-database}:${DC_ORO_DATABASE_PORT:-5432}/${DC_ORO_DATABASE_DBNAME:-app}"}'
      - 'ORO_DB_HOST=${DC_ORO_DATABASE_HOST:-database}'
      - 'ORO_DB_PORT=${DC_ORO_DATABASE_PORT:-5432}'
      - 'ORO_DB_NAME=${DC_ORO_DATABASE_DBNAME:-app}'
      - 'ORO_DB_USER=${DC_ORO_DATABASE_USER:-app}'
      - 'ORO_DB_PASSWORD=${DC_ORO_DATABASE_PASSWORD:-app}'
      - 'ORO_SEARCH_URL=${DC_ORO_SEARCH_URI:-"elasticsearch://search:9200"}'
      - 'ORO_SEARCH_DSN=${DC_ORO_SEARCH_URI:-"elasticsearch://search:9200"}'
      - 'ORO_SEARCH_ENGINE_DSN=${DC_ORO_SEARCH_URI:-"elasticsearch://search:9200"}?prefix=oro_search'
      - 'ORO_WEBSITE_SEARCH_ENGINE_DSN=${DC_ORO_SEARCH_URI:-"elasticsearch://search:9200"}?prefix=oro_website_search'
      - 'ORO_MQ_DSN=${DC_ORO_MQ_URI:-""}'
      - 'ORO_REDIS_URL=${DC_ORO_REDIS_URI:-""}'
      - 'ORO_REDIS_CACHE_DSN=${DC_ORO_REDIS_URI:-""}/1'
      - 'ORO_REDIS_DOCTRINE_DSN=${DC_ORO_REDIS_URI:-""}/2'
      - 'ORO_REDIS_LAYOUT_DSN=${DC_ORO_REDIS_URI:-""}/3'
      - 'ORO_MAILER_DRIVER=${ORO_MAILER_DRIVER:-smtp}'
      - 'ORO_MAILER_HOST=${ORO_MAILER_HOST-mail}'
      - 'ORO_MAILER_PORT=${ORO_MAILER_PORT-1025}'
      - 'ORO_SECRET=${ORO_SECRET-ThisTokenIsNotSoSecretChangeIt}'
      - 'XHGUI_MONGO_HOSTNAME=mongodb'
      - 'XHGUI_MONGO_DATABASE=xhprof'
      - 'COMPOSER_AUTH=${DC_ORO_COMPOSER_AUTH:-null}'
      - 'NODE_OPTIONS="--max-old-space-size=1024"'
      - 'SYMFONY_ENV=${SYMFONY_ENV:-dev}'
      - 'XDEBUG_MODE=${XDEBUG_MODE_CLI:-off}'
      - 'ORO_SSH_PUBLIC_KEY=${ORO_SSH_PUBLIC_KEY:-null}'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    healthcheck:
      test: "nc -vz -w 1 localhost 22"
      start_period: 5s
      interval: 5s
      retries: 18
    restart: always

volumes:
  appcode:
    external: true
    name: ${DC_ORO_NAME:-unnamed}_appcode
  ssh-hostkeys:
    driver: local
