services:
  database:
    image: 'busybox'
    container_name: ${DC_ORO_NAME:-unnamed}_database
    hostname: database.${DC_ORO_NAME:-unnamed}.docker.local
    command: sleep infinity
    networks:
      - 'app'
    restart: always
    healthcheck:
      test: "sh -c 'exit 0'"
  fpm:
    container_name: "${DC_ORO_NAME:-unnamed}_fpm_${DC_ORO_PHP_VERSION:-8.3}-${DC_ORO_NODE_VERSION:-20}-${DC_ORO_COMPOSER_VERSION:-2}"
    hostname: fpm.${DC_ORO_NAME:-unnamed}.docker.local
    build:
      dockerfile: Dockerfile.${DC_ORO_PHP_VERSION:-8.3}.${DC_ORO_PHP_DIST:-alpine}
      context: "${DC_ORO_CONFIG_DIR:-.}/docker/php-node-symfony"
      args:
        APP_DIR: "${DC_ORO_APPDIR:-/var/www}"
        PHP_VERSION: "${DC_ORO_PHP_VERSION:-8.3}"
        NODE_VERSION: "${DC_ORO_NODE_VERSION:-20}"
        PHP_USER_NAME: "${DC_ORO_PHP_USER_NAME:-developer}"
        PHP_USER_GROUP: "${DC_ORO_PHP_USER_GROUP:-developer}"
        PHP_UID: "${DC_ORO_PHP_UID:-1000}"
        PHP_GID: "${DC_ORO_PHP_GID:-1000}"
        COMPOSER_VERSION: "${DC_ORO_COMPOSER_VERSION:-2}"
    user: "${DC_ORO_USER_NAME:-developer}"
    command: php-fpm -R
    volumes:
      - "appcode:${DC_ORO_APPDIR:-/var/www}:consistent"
      - "home-user:/home/${DC_ORO_PHP_USER_NAME:-developer}"
      - "home-root:/root"
      - "${DC_ORO_CONFIG_DIR:-.}/docker/php-node-symfony/msmtprc:/home/${DC_ORO_PHP_USER_NAME:-developer}/.msmtprc:ro"
      - "${DC_ORO_CONFIG_DIR:-.}/docker/php-node-symfony/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint:ro"
    working_dir: "${DC_ORO_APPDIR:-/var/www}"
    networks:
      - 'app'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - 'APP_DIR=${DC_ORO_APPDIR:-/var/www}'
      - 'DC_ORO_APPDIR=${DC_ORO_APPDIR:-/var/www}'
      - 'DC_ORO_DATABASE_HOST=${DC_ORO_DATABASE_HOST:-database}'
      - 'DC_ORO_DATABASE_PORT=${DC_ORO_DATABASE_PORT:-3306}'
      - 'DC_ORO_DATABASE_USER=${DC_ORO_DATABASE_USER:-app}'
      - 'DC_ORO_DATABASE_PASSWORD=${DC_ORO_DATABASE_PASSWORD:-app}'
      - 'DC_ORO_DATABASE_DBNAME=${DC_ORO_DATABASE_DBNAME:-app}'
      - 'ORO_DB_URL=${DC_ORO_DATABASE_URI}'
      - 'ORO_DB_DSN=${DC_ORO_DATABASE_URI}'
      - 'ORO_DB_HOST=${DC_ORO_DATABASE_HOST:-database}'
      - 'ORO_DB_PORT=${DC_ORO_DATABASE_PORT:-3306}'
      - 'ORO_DB_NAME=${DC_ORO_DATABASE_DBNAME:-app}'
      - 'ORO_DB_USER=${DC_ORO_DATABASE_USER:-app}'
      - 'ORO_DB_PASSWORD=${DC_ORO_DATABASE_PASSWORD:-app}'
      - 'ORO_MAILER_DRIVER=${ORO_MAILER_DRIVER-smtp}'
      - 'ORO_MAILER_HOST=${ORO_MAILER_HOST-mail}'
      - 'ORO_MAILER_PORT=${ORO_MAILER_PORT-1025}'
      - 'ORO_SECRET=${ORO_SECRET-ThisTokenIsNotSoSecretChangeIt}'
      - 'XHGUI_MONGO_HOSTNAME=mongodb'
      - 'XHGUI_MONGO_DATABASE=xhprof'
      - 'COMPOSER_AUTH=${DC_ORO_COMPOSER_AUTH:-null}'
      - 'NODE_OPTIONS="--max-old-space-size=1024"'
      - 'SYMFONY_ENV=${SYMFONY_ENV:-dev}'
      - 'XDEBUG_MODE=${XDEBUG_MODE_FPM:-off}'
    depends_on:
      database:
        condition: service_healthy
    restart: always
    healthcheck:
      test: /bin/bash -c "</dev/tcp/localhost/9000"
      start_period: 5s
      interval: 5s
      retries: 18
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  cli:
    container_name: "${DC_ORO_NAME:-unnamed}_cli_${DC_ORO_PHP_VERSION:-8.3}-${DC_ORO_NODE_VERSION:-20}-${DC_ORO_COMPOSER_VERSION:-2}"
    hostname: cli.${DC_ORO_NAME:-unnamed}.docker.local
    build:
      dockerfile: Dockerfile.${DC_ORO_PHP_VERSION:-8.3}.${DC_ORO_PHP_DIST:-alpine}
      context: "${DC_ORO_CONFIG_DIR:-.}/docker/php-node-symfony"
      args:
        APP_DIR: "${DC_ORO_APPDIR:-/var/www}"
        PHP_VERSION: "${DC_ORO_PHP_VERSION:-8.3}"
        NODE_VERSION: "${DC_ORO_NODE_VERSION:-20}"
        PHP_USER_NAME: "${DC_ORO_PHP_USER_NAME:-developer}"
        PHP_USER_GROUP: "${DC_ORO_PHP_USER_GROUP:-developer}"
        PHP_UID: "${DC_ORO_PHP_UID:-1000}"
        PHP_GID: "${DC_ORO_PHP_GID:-1000}"
        COMPOSER_VERSION: "${DC_ORO_COMPOSER_VERSION:-2}"
    user: "${DC_ORO_USER_NAME:-developer}"
    volumes:
      - "appcode:${DC_ORO_APPDIR:-/var/www}:consistent"
      - "home-user:/home/${DC_ORO_PHP_USER_NAME:-developer}"
      - "home-root:/root"
      - "${DC_ORO_CONFIG_DIR:-.}/docker/php-node-symfony/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint:ro"
    working_dir: "${DC_ORO_APPDIR:-/var/www}"
    networks:
      - 'app'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - 'APP_DIR=${DC_ORO_APPDIR:-/var/www}'
      - 'DC_ORO_APPDIR=${DC_ORO_APPDIR:-/var/www}'
      - 'DC_ORO_DATABASE_HOST=${DC_ORO_DATABASE_HOST:-database}'
      - 'DC_ORO_DATABASE_PORT=${DC_ORO_DATABASE_PORT:-3306}'
      - 'DC_ORO_DATABASE_USER=${DC_ORO_DATABASE_USER:-app}'
      - 'DC_ORO_DATABASE_PASSWORD=${DC_ORO_DATABASE_PASSWORD:-app}'
      - 'DC_ORO_DATABASE_DBNAME=${DC_ORO_DATABASE_DBNAME:-app}'
      - 'ORO_DB_URL=${DC_ORO_DATABASE_URI}'
      - 'ORO_DB_DSN=${DC_ORO_DATABASE_URI}'
      - 'ORO_DB_HOST=${DC_ORO_DATABASE_HOST:-database}'
      - 'ORO_DB_PORT=${DC_ORO_DATABASE_PORT:-3306}'
      - 'ORO_DB_NAME=${DC_ORO_DATABASE_DBNAME:-app}'
      - 'ORO_DB_USER=${DC_ORO_DATABASE_USER:-app}'
      - 'ORO_DB_PASSWORD=${DC_ORO_DATABASE_PASSWORD:-app}'
      - 'ORO_MAILER_DRIVER=${ORO_MAILER_DRIVER-smtp}'
      - 'ORO_MAILER_HOST=${ORO_MAILER_HOST-mail}'
      - 'ORO_MAILER_PORT=${ORO_MAILER_PORT-1025}'
      - 'ORO_SECRET=${ORO_SECRET-ThisTokenIsNotSoSecretChangeIt}'
      - 'XHGUI_MONGO_HOSTNAME=mongodb'
      - 'XHGUI_MONGO_DATABASE=xhprof'
      - 'COMPOSER_AUTH=${DC_ORO_COMPOSER_AUTH:-null}'
      - 'NODE_OPTIONS="--max-old-space-size=1024"'
      - 'SYMFONY_ENV=${SYMFONY_ENV:-dev}'
      - 'XDEBUG_MODE=${XDEBUG_MODE_CLI:-off}'
    depends_on:
      database:
        condition: service_healthy
      search:
        condition: service_healthy
      mq:
        condition: service_healthy
      redis:
        condition: service_healthy
      mail:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  consumer:
    container_name: "${DC_ORO_NAME:-unnamed}_consumer_${DC_ORO_PHP_VERSION:-8.3}-${DC_ORO_NODE_VERSION:-20}-${DC_ORO_COMPOSER_VERSION:-2}"
    hostname: consumer.${DC_ORO_NAME:-unnamed}.docker.local
    profiles: ["consumer"]
    build:
      dockerfile: Dockerfile.${DC_ORO_PHP_VERSION:-8.3}.${DC_ORO_PHP_DIST:-alpine}
      context: "${DC_ORO_CONFIG_DIR:-.}/docker/php-node-symfony"
      args:
        APP_DIR: "${DC_ORO_APPDIR:-/var/www}"
        PHP_VERSION: "${DC_ORO_PHP_VERSION:-8.3}"
        NODE_VERSION: "${DC_ORO_NODE_VERSION:-20}"
        PHP_USER_NAME: "${DC_ORO_PHP_USER_NAME:-developer}"
        PHP_USER_GROUP: "${DC_ORO_PHP_USER_GROUP:-developer}"
        PHP_UID: "${DC_ORO_PHP_UID:-1000}"
        PHP_GID: "${DC_ORO_PHP_GID:-1000}"
        COMPOSER_VERSION: "${DC_ORO_COMPOSER_VERSION:-2}"
    user: "${DC_ORO_USER_NAME:-developer}"
    command: until [ -f bin/console ]; do sleep 1; done; php bin/console oro:message-queue:consume -vv
    volumes:
      - "appcode:${DC_ORO_APPDIR:-/var/www}:consisten"
      - "home-user:/home/${DC_ORO_PHP_USER_NAME:-developer}"
      - "home-root:/root"
      - "${DC_ORO_CONFIG_DIR:-.}/docker/php-node-symfony/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint:ro"
    working_dir: "${DC_ORO_APPDIR:-/var/www}"
    networks:
      - 'app'
    restart: always
    environment:
      - 'DC_ORO_DATABASE_HOST=${DC_ORO_DATABASE_HOST:-database}'
      - 'DC_ORO_DATABASE_PORT=${DC_ORO_DATABASE_PORT:-3306}'
      - 'DC_ORO_DATABASE_USER=${DC_ORO_DATABASE_USER:-app}'
      - 'DC_ORO_DATABASE_PASSWORD=${DC_ORO_DATABASE_PASSWORD:-app}'
      - 'DC_ORO_DATABASE_DBNAME=${DC_ORO_DATABASE_DBNAME:-app}'
      - 'ORO_DB_URL=${DC_ORO_DATABASE_URI}'
      - 'ORO_DB_DSN=${DC_ORO_DATABASE_URI}'
      - 'ORO_DB_HOST=${DC_ORO_DATABASE_HOST:-database}'
      - 'ORO_DB_PORT=${DC_ORO_DATABASE_PORT:-3306}'
      - 'ORO_DB_NAME=${DC_ORO_DATABASE_DBNAME:-app}'
      - 'ORO_DB_USER=${DC_ORO_DATABASE_USER:-app}'
      - 'ORO_DB_PASSWORD=${DC_ORO_DATABASE_PASSWORD:-app}'
      - 'ORO_MAILER_DRIVER=${ORO_MAILER_DRIVER-smtp}'
      - 'ORO_MAILER_HOST=${ORO_MAILER_HOST-mail}'
      - 'ORO_MAILER_PORT=${ORO_MAILER_PORT-1025}'
      - 'ORO_SECRET=${ORO_SECRET-ThisTokenIsNotSoSecretChangeIt}'
      - 'XHGUI_MONGO_HOSTNAME=mongodb'
      - 'XHGUI_MONGO_DATABASE=xhprof'
      - 'COMPOSER_AUTH=${DC_ORO_COMPOSER_AUTH:-null}'
      - 'NODE_OPTIONS="--max-old-space-size=1024"'
      - 'SYMFONY_ENV=${SYMFONY_ENV:-dev}'
      - 'XDEBUG_MODE=${XDEBUG_MODE_CONSUMER:-off}'
    depends_on:
      database:
        condition: service_healthy
      search:
        condition: service_healthy
      mq:
        condition: service_healthy
      redis:
        condition: service_healthy
      mail:
        condition: service_healthy
      fpm:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  websocket:
    container_name: "${DC_ORO_NAME:-unnamed}_websocket_${DC_ORO_PHP_VERSION:-8.3}-${DC_ORO_NODE_VERSION:-20}-${DC_ORO_COMPOSER_VERSION:-2}"
    hostname: websocket.${DC_ORO_NAME:-unnamed}.docker.local
    profiles: ["websocket"]
    build:
      dockerfile: Dockerfile.${DC_ORO_PHP_VERSION:-8.3}.${DC_ORO_PHP_DIST:-alpine}
      context: "${DC_ORO_CONFIG_DIR:-.}/docker/php-node-symfony"
      args:
        APP_DIR: "${DC_ORO_APPDIR:-/var/www}"
        PHP_VERSION: "${DC_ORO_PHP_VERSION:-8.3}"
        NODE_VERSION: "${DC_ORO_NODE_VERSION:-20}"
        PHP_USER_NAME: "${DC_ORO_PHP_USER_NAME:-developer}"
        PHP_USER_GROUP: "${DC_ORO_PHP_USER_GROUP:-developer}"
        PHP_UID: "${DC_ORO_PHP_UID:-1000}"
        PHP_GID: "${DC_ORO_PHP_GID:-1000}"
        COMPOSER_VERSION: "${DC_ORO_COMPOSER_VERSION:-2}"
    user: "${DC_ORO_USER_NAME:-developer}"
    command: until [ -f bin/console ]; do sleep 1; done; php bin/console gos:websocket:server
    volumes:
      - "appcode:${DC_ORO_APPDIR:-/var/www}:consistent"
      - "home-user:/home/${DC_ORO_PHP_USER_NAME:-developer}"
      - "home-root:/root"
      - "${DC_ORO_CONFIG_DIR:-.}/docker/php-node-symfony/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint:ro"
    working_dir: "${DC_ORO_APPDIR:-/var/www}"
    networks:
      - 'app'
    restart: always
    environment:
      - 'DC_ORO_DATABASE_HOST=${DC_ORO_DATABASE_HOST:-database}'
      - 'DC_ORO_DATABASE_PORT=${DC_ORO_DATABASE_PORT:-3306}'
      - 'DC_ORO_DATABASE_USER=${DC_ORO_DATABASE_USER:-app}'
      - 'DC_ORO_DATABASE_PASSWORD=${DC_ORO_DATABASE_PASSWORD:-app}'
      - 'DC_ORO_DATABASE_DBNAME=${DC_ORO_DATABASE_DBNAME:-app}'
      - 'ORO_DB_URL=${DC_ORO_DATABASE_URI}'
      - 'ORO_DB_DSN=${DC_ORO_DATABASE_URI}'
      - 'ORO_DB_URL=${DC_ORO_DATABASE_URI}'
      - 'ORO_DB_DSN=${DC_ORO_DATABASE_URI}'
      - 'ORO_DB_HOST=${DC_ORO_DATABASE_HOST:-database}'
      - 'ORO_DB_PORT=${DC_ORO_DATABASE_PORT:-3306}'
      - 'ORO_DB_NAME=${DC_ORO_DATABASE_DBNAME:-app}'
      - 'ORO_DB_USER=${DC_ORO_DATABASE_USER:-app}'
      - 'ORO_DB_PASSWORD=${DC_ORO_DATABASE_PASSWORD:-app}'
      - 'ORO_SEARCH_URL=${DC_ORO_SEARCH_URI}'
      - 'ORO_SEARCH_DSN=${DC_ORO_SEARCH_URI}'
      - 'ORO_SEARCH_ENGINE_DSN=${DC_ORO_SEARCH_URI}?prefix=oro_search'
      - 'ORO_WEBSITE_SEARCH_ENGINE_DSN=${DC_ORO_SEARCH_URI}?prefix=oro_website_search'
      - 'ORO_MQ_DSN=${DC_ORO_MQ_URI}'
      - 'ORO_REDIS_URL=${DC_ORO_REDIS_URI}'
      - 'ORO_REDIS_CACHE_DSN=${DC_ORO_REDIS_URI}/1'
      - 'ORO_REDIS_DOCTRINE_DSN=${DC_ORO_REDIS_URI}/2'
      - 'ORO_REDIS_LAYOUT_DSN=${DC_ORO_REDIS_URI}/3'
      - 'ORO_MAILER_DRIVER=${ORO_MAILER_DRIVER-smtp}'
      - 'ORO_MAILER_HOST=${ORO_MAILER_HOST-mail}'
      - 'ORO_MAILER_PORT=${ORO_MAILER_PORT-1025}'
      - 'ORO_SECRET=${ORO_SECRET-ThisTokenIsNotSoSecretChangeIt}'
      - 'XHGUI_MONGO_HOSTNAME=mongodb'
      - 'XHGUI_MONGO_DATABASE=xhprof'
      - 'COMPOSER_AUTH=${DC_ORO_COMPOSER_AUTH:-null}'
      - 'NODE_OPTIONS="--max-old-space-size=1024"'
      - 'SYMFONY_ENV=${SYMFONY_ENV:-dev}'
      - 'XDEBUG_MODE=${XDEBUG_MODE_WEBSOCKET:-off}'
    depends_on:
      database:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  mail:
    image: "cd2team/mailhog"
    container_name: ${DC_ORO_NAME:-unnamed}_mail
    hostname: mail.${DC_ORO_NAME:-unnamed}.docker.local
    ports:
      - "${DC_ORO_MAIL_BIND_HOST:-127.0.0.1}:${DC_ORO_PORT_MAIL_WEBGUI:-${DC_ORO_PORT_PREFIX}25}:8025"
    networks:
      - 'app'
    restart: always
    healthcheck:
      test: "nc -vz -w 1 localhost 8025"
      start_period: 5s
      interval: 5s
      retries: 18

  xhgui:
    image: "xhgui/xhgui:0.18.3"
    hostname: xhgui.${DC_ORO_NAME:-unnamed}.docker.local
    profiles: ["xhprof"]
    volumes:
      - "${DC_ORO_CONFIG_DIR:-.}/docker/xhgui/config:/var/www/xhgui/config"
      - "${DC_ORO_CONFIG_DIR:-.}/docker/xhgui/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
    environment:
      - XHGUI_MONGO_HOSTNAME=mongodb
      - XHGUI_MONGO_DATABASE=xhprof
    ports:
      - "${DC_ORO_XHGUI_BIND_HOST:-127.0.0.1}:${DC_ORO_PORT_XHGUI:-${DC_ORO_PORT_PREFIX}81}:80"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - 'app'
    restart: always
    healthcheck:
      test: nc -vz -w 1 localhost 80
      start_period: 5s
      interval: 5s
      retries: 18
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  mongodb:
    image: percona/percona-server-mongodb:4.4
    hostname: mongodb.${DC_ORO_NAME:-unnamed}.docker.local
    container_name: ${DC_ORO_NAME:-unnamed}_mongodb
    profiles: ["xhprof"]
    # (case sensitive) engine: mmapv1, rocksdb, wiredTiger, inMemory
    command: --storageEngine=wiredTiger
    environment:
      - MONGO_INITDB_DATABASE=xhprof
    volumes:
      - '${DC_ORO_CONFIG_DIR:-.}/docker/mongo/initdb.d:/docker-entrypoint-initdb.d'
    networks:
      - 'app'
    restart: always
    healthcheck:
      test: mongo --quiet --eval 'db.runCommand("ping").ok' xhgui
      start_period: 5s
      interval: 5s
      retries: 18
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  search:
    image: '${DC_ORO_ELASTICSEARCH_IMAGE:-docker.elastic.co/elasticsearch/elasticsearch}:${DC_ORO_ELASTICSEARCH_VERSION:-8.9.1}'
    hostname: search.${DC_ORO_NAME:-unnamed}.docker.local
    container_name: ${DC_ORO_NAME:-unnamed}_search
    volumes:
      - "search-data:/usr/share/elasticsearch/data:delegated"
    environment:
      ES_JAVA_OPTS: '${ES_JAVA_OPTS:--Xms256m -Xmx2048m}'
      ELASTIC_PASSWORD: elastic
      discovery.type: 'single-node'
    ports:
      - "${DC_ORO_ES_BIND_HOST:-127.0.0.1}:${DC_ORO_PORT_ELASTICSEARCH:-${DC_ORO_PORT_PREFIX}92}:9200"
    networks:
      - 'app'
    restart: always
    healthcheck:
      test: /bin/bash -c "</dev/tcp/localhost/9200"
      start_period: 5s
      interval: 5s
      retries: 18
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  nginx:
    image: ${DC_ORO_NAME:-unnamed}_nginx
    hostname: nginx.${DC_ORO_NAME:-unnamed}.docker.local
    container_name: ${DC_ORO_NAME:-unnamed}_nginx
    build:
      context: "${DC_ORO_CONFIG_DIR:-.}/docker/nginx"
      args:
        APP_DIR: "${DC_ORO_APPDIR:-/var/www}"
    depends_on:
      fpm:
        condition: service_healthy
    ports:
      - '${DC_ORO_NGINX_BIND_HOST:-127.0.0.1}:${DC_ORO_PORT_NGINX:-${DC_ORO_PORT_PREFIX}80}:80'
    volumes:
      - "appcode:${DC_ORO_APPDIR:-/var/www}:ro"
    working_dir: "${DC_ORO_APPDIR:-/var/www}"
    networks:
      - 'app'
      - 'shared'
    restart: always
    environment:
      - 'APP_DIR=${DC_ORO_APPDIR:-/var/www}'
      - 'DC_ORO_APPDIR=${DC_ORO_APPDIR:-/var/www}'
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.compress-${DC_ORO_NAME:-unnamed}.compress=true"
      - "traefik.http.middlewares.cors-${DC_ORO_NAME:-unnamed}.headers.accessControlAllowCredentials=true"
      - "traefik.http.middlewares.cors-${DC_ORO_NAME:-unnamed}.headers.accessControlAllowHeaders=*"
      - "traefik.http.middlewares.cors-${DC_ORO_NAME:-unnamed}.headers.accessControlAllowMethods=PUT,GET,POST,HEAD,PATCH,DELETE"
      - "traefik.http.middlewares.cors-${DC_ORO_NAME:-unnamed}.headers.accessControlAllowOriginList=*"
      - "traefik.http.middlewares.resp-headers-${DC_ORO_NAME:-unnamed}.headers.customResponseHeaders.X-Project-Name=${DC_ORO_NAME:-unnamed}"
      - "traefik.http.routers.${DC_ORO_NAME:-unnamed}.entrypoints=default"
      - "traefik.http.routers.${DC_ORO_NAME:-unnamed}.middlewares=compress-${DC_ORO_NAME:-unnamed},cors-${DC_ORO_NAME:-unnamed},resp-headers-${DC_ORO_NAME:-unnamed}"
      - "traefik.http.routers.${DC_ORO_NAME:-unnamed}.rule=Host(`${DC_ORO_NAME:-unnamed}.docker.local`)"
      - "traefik.http.routers.${DC_ORO_NAME:-unnamed}.service=${DC_ORO_NAME:-unnamed}"
      - "traefik.http.services.${DC_ORO_NAME:-unnamed}.loadbalancer.server.port=80"
      - "traefik.http.services.${DC_ORO_NAME:-unnamed}.loadbalancer.server.scheme=http"
    healthcheck:
      test: /bin/bash -c "</dev/tcp/localhost/80"
      start_period: 5s
      interval: 5s
      retries: 18
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  mq:
    image: oroinc/rabbitmq:3.9-1-management-alpine
    hostname: mq.${DC_ORO_NAME:-unnamed}.docker.local
    container_name: ${DC_ORO_NAME:-unnamed}_mq
    ports:
      - "${DC_ORO_ES_BIND_HOST:-127.0.0.1}:${DC_ORO_PORT_RABBITMQ:-${DC_ORO_PORT_PREFIX}72}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${DC_ORO_MQ_USER:-app}
      RABBITMQ_DEFAULT_PASS: ${DC_ORO_MQ_PASSWORD:-app}
    healthcheck:
      test: nc -vz -w 1 localhost 5672
      start_period: 5s
      interval: 5s
      retries: 18
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  redis:
    image: redis:6.2
    hostname: redis.${DC_ORO_NAME:-unnamed}.docker.local
    container_name: ${DC_ORO_NAME:-unnamed}_redis
    restart: always
    healthcheck:
      test: nc -vz -w 1 localhost 6379
      start_period: 5s
      interval: 5s
      retries: 18
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

networks:
  app:
    name: ${DC_ORO_NAME:-unnamed}_app_net
  shared:
    external: true
    name: dc_shared_net

volumes:
  home-user:
    driver: local
  home-root:
    driver: local
  search-data:
    driver: local
