services:
  mutagen:
    container_name: "${DC_ORO_NAME:-unnamed}_mutagen_${DC_ORO_PHP_VERSION:-8.1}-${DC_ORO_NODE_VERSION:-16}-${DC_ORO_COMPOSER_VERSION:-2}"
    hostname: mutagen.${DC_ORO_NAME:-unnamed}.docker.local
    build:
      context: "${DC_ORO_CONFIG_DIR:-.}/docker/php-node-symfony"
      dockerfile: Dockerfile.${DC_ORO_PHP_VERSION:-8.3}.${DC_ORO_PHP_DIST:-alpine}
      args:
        APP_DIR: "${DC_ORO_APPDIR:-/var/www}"
        PHP_VERSION: ${DC_ORO_PHP_VERSION:-8.1}
        NODE_VERSION: ${DC_ORO_NODE_VERSION:-16}
        PHP_USER_NAME: ${DC_ORO_PHP_USER_NAME:-developer}
        PHP_USER_GROUP: ${DC_ORO_PHP_USER_GROUP:-developer}
        PHP_UID: ${DC_ORO_PHP_UID:-1000}
        PHP_GID: ${DC_ORO_PHP_GID:-1000}
        COMPOSER_VERSION: "${DC_ORO_COMPOSER_VERSION:-2}"
    environment:
      - 'APP_DIR=${DC_ORO_APPDIR:-/var/www}'
      - 'DC_ORO_APPDIR=${DC_ORO_APPDIR:-/var/www}'
    volumes:
      - appcode:${DC_ORO_APPDIR:-/var/www}:consistent
    command: "sleep infinity"
    working_dir: "${DC_ORO_APPDIR:-/var/www}"
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    networks:
      - 'app'
    restart: on-failure:3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
  cli:
    depends_on:
      mutagen:
        condition: service_started

volumes:
  appcode:
    driver: local
    driver_opts: {}
