# .github/workflows/build-multiarch.yml
name: Build & Publish multi‑arch images to GHCR

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:

  # 1) PHP 7.4 + Node LTS (16,18,20) + Composer (1,2) + Variant (alpine)
  build-7.4:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:      [7.4]
        node:     [16, 18, 20]
        composer: [1, 2]
        variant:  [alpine]
    steps:
      - uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build & push PHP ${{ matrix.php }} (Node ${{ matrix.node }}, Composer ${{ matrix.composer }}, ${{ matrix.variant }})
        uses: docker/build-push-action@v4
        with:
          context: .
          file: compose/docker/php-node-symfony/Dockerfile.${{ matrix.php }}.${{ matrix.variant }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/orodc-php-node-symfony:${{ matrix.php }}-${{ matrix.node }}-${{ matrix.composer }}-${{ matrix.variant }}
          build-args: |
            PHP_VERSION=${{ matrix.php }}
            NODE_VERSION=${{ matrix.node }}
            COMPOSER_VERSION=${{ matrix.composer }}


  # 2) PHP 8.1–8.4 + Node LTS (18,20) + Composer (2) + Variant (alpine)
  build-8x:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:      [8.1, 8.2, 8.3, 8.4]
        node:     [18, 20]
        composer: [2]
        variant:  [alpine]
    steps:
      - uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build & push PHP ${{ matrix.php }} (Node ${{ matrix.node }}, Composer ${{ matrix.composer }}, ${{ matrix.variant }})
        uses: docker/build-push-action@v4
        with:
          context: .
          file: compose/docker/php-node-symfony/Dockerfile.${{ matrix.php }}.${{ matrix.variant }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/orodc-php-node-symfony:${{ matrix.php }}-${{ matrix.node }}-${{ matrix.composer }}-${{ matrix.variant }}
          build-args: |
            PHP_VERSION=${{ matrix.php }}
            NODE_VERSION=${{ matrix.node }}
            COMPOSER_VERSION=${{ matrix.composer }}