name: Build & Publish nginx multi-arch images to GHCR

on:
  push:
    branches: [ master ]
    paths:
      - 'compose/docker/nginx/**'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-nginx-amd64:
    name: Build Nginx AMD64
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build & Push AMD64 Image
        uses: docker/build-push-action@v5
        with:
          context: compose/docker/nginx
          file: compose/docker/nginx/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/orodc-nginx:amd64
          cache-from: type=gha,scope=nginx-amd64
          cache-to: type=gha,mode=max,scope=nginx-amd64

  build-nginx-arm64:
    name: Build Nginx ARM64
    runs-on: [self-hosted, Linux, ARM64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build & Push ARM64 Image
        uses: docker/build-push-action@v5
        with:
          context: compose/docker/nginx
          file: compose/docker/nginx/Dockerfile
          platforms: linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/orodc-nginx:arm64
          cache-from: type=gha,scope=nginx-arm64
          cache-to: type=gha,mode=max,scope=nginx-arm64

  create-nginx-manifest:
    name: Create multi-arch manifest
    needs: [build-nginx-amd64, build-nginx-arm64]
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create and push multi-arch manifest
        run: |
          # Create multi-arch manifest
          docker buildx imagetools create \
            --tag ghcr.io/${{ github.repository_owner }}/orodc-nginx:latest \
            ghcr.io/${{ github.repository_owner }}/orodc-nginx:amd64 \
            ghcr.io/${{ github.repository_owner }}/orodc-nginx:arm64
          
          # Also create without :latest suffix for backward compatibility
          docker buildx imagetools create \
            --tag ghcr.io/${{ github.repository_owner }}/orodc-nginx \
            ghcr.io/${{ github.repository_owner }}/orodc-nginx:amd64 \
            ghcr.io/${{ github.repository_owner }}/orodc-nginx:arm64