name: Build & Publish nginx multi-arch images to GHCR

on:
  push:
    branches: [ master ]
    paths:
      - 'compose/docker/nginx/**'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-nginx:
    name: Build Nginx images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build & Push Nginx Docker Image
        uses: docker/build-push-action@v4
        with:
          context: compose/docker/nginx
          file: compose/docker/nginx/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/nginx